### ISSUE TITLE
Graceful handling of a server failure in Beanstalk:Pool

### ISSUE THREAD

**Issue by jbaudanza** [kr/beanstalk-client-ruby#10]
Currently, if a beanstalkd dies, the client eagerly tries to reconnect upon the next request.  If the server is offline, this will cause unnecessary delays while these connection attempts timeout.  In this case it would be preferable to remove the failed server from the pool until an administrator can attend to the matter.

I've implemented something like this in my branch 2fbf670a85081e9d7f74176793f18fdeea715fef

Let me know what you think.  If you'd like I can prepare a pull request

**Comment by kr** [comment]
Hi! I'm going through all the open issues in beanstalk-client-ruby
to let you know that there's a new client at
https://github.com/beanstalkd/beaneater.

I'm not maintaining this repo any more, but @nesquena is actively
maintaining beaneater and he'll definitely handle the issue if it's
still relevant over there.
