### ISSUE TITLE
Beanstalk::Job doesn't delete buried job

### ISSUE THREAD

**Issue by crawlik** [kr/beanstalk-client-ruby#18]
I run into a strange issue trying to delete a buried job using Beanstalk::Job instance. See the snippet below...

``` ruby
require 'beanstalk-client'

beanstalk = Beanstalk::Pool.new(['localhost:11300'], 'tube')

# add message
beanstalk.put('0')

# bury message
job = beanstalk.reserve
job.bury

p job = beanstalk.peek_buried
job.delete
p beanstalk.peek_buried
```

Job is NOT deleted!

(job server=localhost:11300 id=20397 size=1)
(job server=localhost:11300 id=20397 size=1)

When you use delete method in Connection class it magically deletes the job.

``` ruby
beanstalk.last_conn.delete(job.id)
```

Any idea why it is happening?

**Comment by denniskuczynski** [comment]
It looks like the Job::bury call marks the job as no longer reserved, and the Job::delete call returns immediately if the job is not reserved.  The connection delete call does not do a check to see if the job is reserved.  (Not sure which version is more correct.)

``` ruby
  def delete()
    return if !@reserved
    @conn.delete(id)
    @reserved = false
  end

  def bury(newpri=nil)
    return if !@reserved
    @conn.bury(id, newpri || pri)
    @reserved = false
  end
```

**Comment by crawlik** [comment]
@denniskuczynski, thanks for clarification. According to state diagram http://beanstalkc.readthedocs.org/en/latest/tutorial.html#advanced-operation job can be deleted when it is either in  `RESERVED` or `BURIED` state. So I would argue that we should not check @reserved at all and let beanstalk server do the checking and respond with an error if delete is called when job is in a wrong state. Any reason why it might not work?

**Comment by denniskuczynski** [comment]
@crawlik You're right.  It looks like removing the @reserved check from the delete call matches up the functionality to the docs.

``` ruby
return if !@reserved
```

**Comment by nesquena** [comment]
Yeah I think you guys are correct AFAIK no reason a job shouldn't be allowed me to deleted once it was just buried (and marked as unreserved)

**Comment by kr** [comment]
Absolutely right. This library is in desperate need of some
love. Right now it's woefully out of date compared to the
server. Honestly I'm a terrible ruby programmer so if anyone
wants to chip in and send a pull request I'd be most grateful.

(Not just for this issue, I'd also welcome suggestions on
how to clean up the code and reorganize this, and follow
ruby gem best practices.)

**Comment by nesquena** [comment]
@Nico-Taing and I are working on helping out with that. Should have something to show you soon. 

In the meantime ill prepare a pull request for this issue.
