### ISSUE TITLE
Problems with non-string puts

### ISSUE THREAD

**Issue by arp** [kr/beanstalk-client-ruby#2]
Client code assumes that job body is a string with no explicit checks:

```
def put(body, pri=65536, delay=0, ttr=120)
  interact("put #{pri} #{delay} #{ttr} #{body.size}\r\n#{body}\r\n",
           %w(INSERTED BURIED))[0].to_i
end
```

So, when you try to put Numeric job:
    > beanstalk.put(1)

you get lockup because "#{1}" == '1' and 1.size == 8. Server waits for 7 more characters, while client thinks everything is sent.

Probably, better to raise exception when body is not a String, or to do body.to_s before putting.

**Comment by kr** [comment]
Fixed in v1.1.0
