### ISSUE TITLE
Bump gem version to 1.1.1 so it will include the fix for "Count number of bytes, not unicode codepoints."

### ISSUE THREAD

**Issue by ami-navon** [kr/beanstalk-client-ruby#5]
Hi,
The github repository includes the following very useful fix for Ruby 1.9 unicode:
"Count number of bytes, not unicode codepoints."
https://github.com/kr/beanstalk-client-ruby/commit/e80c5da7b9f924fe6ab7c62be27124ca89e47732

Can you bump this gem's version to 1.1.1 so it will include this fix?
Thanks!

**Comment by johnf** [comment]
I'm bumping this one as I'd love my threading support in a released gem too :)

**Comment by kr** [comment]
Hi! I'm going through all the open issues in beanstalk-client-ruby
to let you know that there's a new client at
https://github.com/beanstalkd/beaneater.

I'm not maintaining this repo any more, but @nesquena is actively
maintaining beaneater and he'll definitely handle the issue if it's
still relevant over there.
